"""Deterministically generated by NDS — verifies a customer's paid access
against the NDS Command Center. Do not hand-edit the verification logic;
gate a new endpoint by adding `Depends(require_pro)` to it instead.
"""

import httpx
from fastapi import Header, HTTPException

NDS_API_BASE = 'http://localhost:8000'
VENTURE_ID = 'ff3e6c808acf43f4bf6c2d7f5aec35b7'


async def require_pro(x_license_key: str = Header(default="")) -> str:
    """FastAPI dependency: raises 402 Payment Required unless
    `x_license_key` is a currently active paid entitlement for this
    venture. Customers get their key on the checkout success page after
    paying. Usage: add `Depends(require_pro)` to any endpoint that should
    require payment."""
    if not x_license_key:
        raise HTTPException(status_code=402, detail="Payment required — include your license key as X-License-Key.")

    async with httpx.AsyncClient(timeout=10.0) as client:
        response = await client.get(
            f"{NDS_API_BASE}/ventures/{VENTURE_ID}/entitlements/verify",
            params={"key": x_license_key},
        )
    if response.status_code != 200 or not response.json().get("entitled"):
        raise HTTPException(status_code=402, detail="Payment required — this license key is not active.")
    return x_license_key
